development:
  adapter: postgresql
  database: karate_dev
  username: postgres
  password: admin
  port: 5432

test:
  adapter: postgresql
  database: karate_test
  username: postgres
  password: admin
  port: 5432

production:
  adapter: postgresql
  database: karate_prod
  username: postgres
  password: admin
  port: 5432
